CREATE TABLE IF NOT EXISTS dim_grammy_recognition (
    recognition_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recognition_group     VARCHAR(20) NOT NULL CHECK (recognition_group IN ('Grammy', 'No-Grammy')),
    artist_grammy_wins_range VARCHAR(10) NOT NULL CHECK (artist_grammy_wins_range IN ('0', '1', '2-4', '5+')),
    wins_range_order       SMALLINT NOT NULL,
    CONSTRAINT uq_recognition UNIQUE (recognition_group, artist_grammy_wins_range),
    CONSTRAINT ck_recognition_consistent CHECK ((recognition_group = 'No-Grammy') = (artist_grammy_wins_range = '0'))
);

CREATE TABLE IF NOT EXISTS dim_popularity_tier (
    popularity_tier_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_name           VARCHAR(20) NOT NULL UNIQUE CHECK (tier_name IN ('Most popular', 'Rest')),
    tier_order          SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_genre (
    genre_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS dim_grammy_category (
    category_key   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name  VARCHAR(300) NOT NULL UNIQUE,
    category_group VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS fact_track (
    track_key           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recognition_key     INTEGER NOT NULL REFERENCES dim_grammy_recognition (recognition_key),
    popularity_tier_key INTEGER NOT NULL REFERENCES dim_popularity_tier (popularity_tier_key),
    track_id            VARCHAR(22) NOT NULL UNIQUE,
    track_name          VARCHAR(500),
    album_name          VARCHAR(500),
    popularity          NUMERIC(5,2) NOT NULL CHECK (popularity BETWEEN 0 AND 100),
    duration_ms         INTEGER NOT NULL CHECK (duration_ms > 0),
    danceability        DOUBLE PRECISION NOT NULL CHECK (danceability BETWEEN 0 AND 1),
    energy              DOUBLE PRECISION NOT NULL CHECK (energy BETWEEN 0 AND 1),
    valence             DOUBLE PRECISION NOT NULL CHECK (valence BETWEEN 0 AND 1),
    acousticness        DOUBLE PRECISION NOT NULL CHECK (acousticness BETWEEN 0 AND 1),
    loudness            DOUBLE PRECISION NOT NULL,
    tempo               DOUBLE PRECISION CHECK (tempo IS NULL OR tempo > 0),
    explicit_flag       SMALLINT NOT NULL CHECK (explicit_flag IN (0, 1)),
    track_count         SMALLINT NOT NULL DEFAULT 1 CHECK (track_count = 1)
);

CREATE TABLE IF NOT EXISTS bridge_track_genre (
    track_key INTEGER NOT NULL REFERENCES fact_track (track_key),
    genre_key INTEGER NOT NULL REFERENCES dim_genre (genre_key),
    PRIMARY KEY (track_key, genre_key)
);

CREATE TABLE IF NOT EXISTS bridge_track_grammy_category (
    track_key    INTEGER NOT NULL REFERENCES fact_track (track_key),
    category_key INTEGER NOT NULL REFERENCES dim_grammy_category (category_key),
    grammy_wins  INTEGER NOT NULL CHECK (grammy_wins >= 1),
    PRIMARY KEY (track_key, category_key)
);

CREATE INDEX IF NOT EXISTS ix_fact_recognition ON fact_track (recognition_key);
CREATE INDEX IF NOT EXISTS ix_fact_tier        ON fact_track (popularity_tier_key);
CREATE INDEX IF NOT EXISTS ix_bridge_genre     ON bridge_track_genre (genre_key);
CREATE INDEX IF NOT EXISTS ix_bridge_category  ON bridge_track_grammy_category (category_key);

-- Fixed dimensions (seeded here so the load never creates them)
INSERT INTO dim_grammy_recognition (recognition_group, artist_grammy_wins_range, wins_range_order) VALUES
    ('No-Grammy', '0', 0), ('Grammy', '1', 1), ('Grammy', '2-4', 2), ('Grammy', '5+', 3)
ON CONFLICT (recognition_group, artist_grammy_wins_range) DO NOTHING;

INSERT INTO dim_popularity_tier (tier_name, tier_order) VALUES
    ('Most popular', 1), ('Rest', 2)
ON CONFLICT (tier_name) DO NOTHING;